# NUMPY (LIBRARY FOR LINEAR ALGEBRA)

## STANDS FOR NUMERICAL PYTHON

### ADVANTAGES OF USING NUMPY

In [2]:
import numpy as np
import sys

In [10]:
#NUMPY ARRAYS TAKE LESSER SPACE THAN NORMAL LISTS
a=[int(i) for i in range(100)]
b=np.arange(100)#creates a numpy array with 100 elements(0-99)
print(a)
print(b)

#get size of one element in list
t=5
#get size of 100 integers(for a normal list)
print('NORMAL LIST :'+str(sys.getsizeof(t)*100))#get size of fxn returns size of object

#get size of one element in numpy array
k=b.itemsize#returns size of one element in a numpy array
#get size of 100 integers stored in numpy array
print("NUMPY ARRAY :"+str(k*100))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
NORMAL LIST :2800
NUMPY ARRAY :400


In [11]:
import time

In [18]:
#NUMPY ARRAYS ARE FASTER THAN LISTS
def additionUsingList(size):
    t1=time.time()
    a=range(size)
    b=range(size)
    c=[a[i]+b[i] for i in range(size)]
    t2=time.time()
    return t2-t1

def additionUsingNumpy(size):
    t1=time.time()
    a=np.arange(size)
    b=np.arange(size)
    c=a+b #make a list after adding each element of a and b and store them in a list
    t2=time.time()
    return t2-t1
size=100000
#WE ARE MULTIPLYING BY 100 TO GET THE TIME IN MILLISECONDS
print("NORMAL LIST :",(additionUsingList(size)*1000))
print("NUMPY ARRAY :",(additionUsingNumpy(size)*1000))    

NORMAL LIST : 34.97958183288574
NUMPY ARRAY : 1.0249614715576172


## NUMPY FUNCTIONS(USING NUMPY)

In [23]:
a=[1,2,3]
b=np.array(a,dtype=int)#used to create a numpy array by passing an iterable
#dtype parameter is used to specify the datatype with which we want to create 
#array
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [24]:
#lists can have multi data types
#lets try to create a numpy array now
a=[1,2,3,'5',6.5]
b=np.array(a)
print(b)#We are getting a numpy array where all elements have changed to string
#this is because numpy arrays have a property of storing homogeneous elements 
#i.e. of the same datatype so we are getting a numpy array of strings

['1' '2' '3' '5' '6.5']


In [25]:
#but we can change that using dtype parameter
a=[1,2,3,'5',6.5]
b=np.array(a,dtype=int)
print(b)

[1 2 3 5 6]


In [26]:
#now lets try to create a numpy array from the given list
a=[1,2,3,'5','av','a']
b=np.array(a)
print(b)

['1' '2' '3' '5' 'av' 'a']


In [27]:
#but if we try to specify dtype as int,we get an error as 'av' and 'a' cannot
#converted to int
a=[1,2,3,'5','av','a']
b=np.array(a,dtype=int)
print(b)


ValueError: invalid literal for int() with base 10: 'av'

In [31]:
a*3#repeat list 

[1, 2, 3, '5', 'av', 'a', 1, 2, 3, '5', 'av', 'a', 1, 2, 3, '5', 'av', 'a']

In [34]:
#creating numpy array using repeat list
b=np.array(a*3)
print(b)

['1' '2' '3' '5' 'av' 'a' '1' '2' '3' '5' 'av' 'a' '1' '2' '3' '5' 'av'
 'a']


### SOME MORE USEFUL FUNCTIONS OF NUMPY FOR CREATING ARRAY

In [35]:
#create an array with only ones
a=np.ones(3)
print(a)#default datatype =flaot

[1. 1. 1.]


In [40]:
a=np.ones(3,dtype=int)
print(a)#change datatype to int

[1 1 1]


In [38]:
#create an array with only zeros
a=np.zeros(4)
print(a)#default datatype =flaot

[0. 0. 0. 0.]


In [42]:
a=np.zeros(3,dtype=int)
print(a)#change datatype to int

[0 0 0]


In [45]:
#CREATE 2-dimensional arrays by passing the dimensions
a=np.zeros((3,4),dtype=int)#passing a tuple as dimensions
print(a,end='\n\n')
b=np.ones((3,4),dtype=int)#passing a tuple as dimensions
print(b)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [48]:
#np.full() method: make an array with all the same elements and of specific size
#by specifying the size and the element for the array
b=np.full(3,5)
print(b)#default dtype is int

[5 5 5]


In [50]:
#creating a 2d array
b=np.full((5,5),5,dtype=float)#pass a tuple as dimensions
print(b)#changed dtype to float

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [53]:
#make a numpy array by specifying dimensions filled with random values
a=np.empty(5)
print(a)#default dtype is float

[8.45569488e-307 3.56011818e-307 1.61323966e-307 4.67296746e-307
 1.69121096e-306]
<class 'numpy.float64'>


In [63]:
#create a 2d array with random values
a=np.empty((6,6),dtype=int)
print(a)

[[-248083944        478        108          0          0          0]
 [         0          0          0    4259932 1868767867  975332708]
 [1919099682 1702125925  840982816 1918967908  544825714 1752459639]
 [1851879968  544042852 1970037110 1851552613 1886272865 1886217518]
 [ 673741172  691219507 2037670956 1765631344 1546220654 1769107566]
 [1630041198  573317673 1667594341 1869182069 1868783470  578055797]]


In [64]:
#ASSIGMENT: CREATE NUMPY ARRAY USING A 2d list
a=[[1,2,3],
   [4,5,6],
   [7,8,9]]
b=np.array(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [66]:
#ASS: create a numpy array of size 10 with all values 0 and fifth value as 1
a=np.zeros(10,dtype=int)
a[4]=5
print(a)

[0 0 0 0 5 0 0 0 0 0]


In [4]:
#np.arange()= gives evenly space values within an interval
'''
start(optional,default=0)
stop
step(optional,default=1)
-->last number is not included
'''
a=np.arange(10)
print(a)
b=np.arange(2,10,2)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[2 4 6 8]


In [10]:
'''
np.linspace()=also gives evenly spaced values in an interval,start & stop 
is inclusive
start
stop
num(optional)=no. of samples we want to get,default is 50
endpoint(optional)=default is true,if set to false stop is not included
'''
a=np.linspace(2,10)
print(a)
#calculate step value
print(a[2]-a[1])
print(a[3]-a[2])
b=np.linspace(2,10,5,dtype=int)#changing dtype to int
print(b)

[ 2.          2.16326531  2.32653061  2.48979592  2.65306122  2.81632653
  2.97959184  3.14285714  3.30612245  3.46938776  3.63265306  3.79591837
  3.95918367  4.12244898  4.28571429  4.44897959  4.6122449   4.7755102
  4.93877551  5.10204082  5.26530612  5.42857143  5.59183673  5.75510204
  5.91836735  6.08163265  6.24489796  6.40816327  6.57142857  6.73469388
  6.89795918  7.06122449  7.2244898   7.3877551   7.55102041  7.71428571
  7.87755102  8.04081633  8.20408163  8.36734694  8.53061224  8.69387755
  8.85714286  9.02040816  9.18367347  9.34693878  9.51020408  9.67346939
  9.83673469 10.        ]
0.16326530612244872
0.16326530612244916
[ 2  4  6  8 10]


In [11]:
b=np.linspace(2,10,5,dtype=int,endpoint=False)#changing dtype to int
print(b)

[2 3 5 6 8]


In [14]:
'''np.identity()=gives an identity matrix (square size)
'''
a=np.identity(3)
print(a)
a=np.identity(3,dtype=int)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [19]:
'''np.eye()=can give a rectangular or square matrix with diagonal elements as 1

'''
a=np.eye(3,dtype=int)
print(a)
a=np.eye(3,5,dtype=int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]


In [22]:
'''np.random.rand()= gives random values in the range 0 to 1
takes size

'''
a=np.random.rand(5)
print(a,end='\n\n')
b=np.random.rand(5,6)
print(b)

[0.15451476 0.46443083 0.79453979 0.42313304 0.66567595]

[[0.83468355 0.29046655 0.4045416  0.25057567 0.93833264 0.64796051]
 [0.51855868 0.98426169 0.73578651 0.97963121 0.27190209 0.7351323 ]
 [0.20276909 0.89457247 0.52640544 0.18972866 0.10838829 0.70467673]
 [0.83843662 0.96982441 0.90437236 0.19964159 0.61817771 0.10003935]
 [0.19194214 0.12473534 0.34157856 0.07738273 0.41392851 0.22705044]]


In [26]:
#get random values in the range 0-10
a=np.random.rand(2,3)*10#scalar multiplication of matrix (not repetition)
print(a)

[[8.9092126  6.53798022 5.04275936]
 [7.32006478 3.73577552 7.87876058]]


In [30]:
#np.random.randint()=generates integer random values
#low:lower interval,by default 0
#high:upper interval
#size
a=np.random.randint(2,size=5)
print(a)#if specified only one value it is taken as upper bound

[0 0 1 0 0]


In [32]:
a=np.random.randint(8,size=(5,4))
print(a)

[[2 6 1 1]
 [5 7 0 2]
 [6 5 7 6]
 [7 4 1 0]
 [1 2 1 4]]


In [33]:
a=np.random.randint(8,10,size=5)#generate in the range 8,9
print(a)

[9 8 9 8 8]


In [35]:
print(a.shape)#tells us dimensions of matrix

(5,)


In [42]:
#to generate one random value integer
np.random.randint(10)

3

In [45]:
#ASS:create an array with inclusive values ranging from 9 to 49
a=np.linspace(9,49)
print(a)

[ 9.          9.81632653 10.63265306 11.44897959 12.26530612 13.08163265
 13.89795918 14.71428571 15.53061224 16.34693878 17.16326531 17.97959184
 18.79591837 19.6122449  20.42857143 21.24489796 22.06122449 22.87755102
 23.69387755 24.51020408 25.32653061 26.14285714 26.95918367 27.7755102
 28.59183673 29.40816327 30.2244898  31.04081633 31.85714286 32.67346939
 33.48979592 34.30612245 35.12244898 35.93877551 36.75510204 37.57142857
 38.3877551  39.20408163 40.02040816 40.83673469 41.65306122 42.46938776
 43.28571429 44.10204082 44.91836735 45.73469388 46.55102041 47.36734694
 48.18367347 49.        ]


In [47]:
#ASS:create an identity matrix of size 5,6
a=np.eye(5,6,dtype=int)
print(a)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


In [58]:
#ASS:cut a rope into 9 parts of 5m AND RETURN THE POINTS WHERE THEY NEED 
#TO BE CUT
a=np.linspace(0,5,10)
print(a)
for i in range(1,10):
    print('%.2f'%a[i])

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44
5.00


## EXAMINING NUMPY ARRAY and slicing them

In [59]:
import numpy as np

In [60]:
'''
numpy objects contain 4 different types of data
data:reference to first element of array
shape:dimensions
dtype=datatype
strides=number of bytes to be skipped to get to the next element
'''
#1d array
li=[1,2,3,4,5]
a=np.array(li)
print(li)
print(a)


[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [61]:
print(a.data)
print(a.shape)
print(a.dtype)
print(a.strides)

(5,)
int32
(4,)


In [68]:
#2d array
li=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
a=np.array(li)
print(li,end='\n\n')
print(a)


[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [69]:
print(a.data)
print(a.shape)
print(a.dtype)
print(a.strides)#we are getting 16,4 because to reach next row we need to skip
#16 bytes of data and to go to the next element in same row we need to skip 4 
#bytes

(4, 4)
int32
(16, 4)


### just like lists we can access elements by providing indexes

In [71]:
#1d array
li=[1,2,3,4,5]
a=np.array(li)
print(li[3])
print(a[3])


4
4


In [77]:
#2d array
li=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
a=np.array(li)
print(li[2][3])
print(a[2][3])#we can access elements by specifying row numbers in separate 
#brackets like lists
print(a[2,3])# or we can access them by providing row and column separated by a
#comma in a bracket in a numpy array

12
12
12


### Slicing elements

In [78]:
#1d array
li=[1,2,3,4,5]
a=np.array(li)
print(li)
print(a)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [80]:
#access elements 2 to 4
print(li[1:4])
print(a[2:4])

[2, 3, 4]
[3 4]


In [81]:
li=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
a=np.array(li)
print(li,end='\n\n')
print(a)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [83]:
#access 10
print(li[2][1])
print(a[2,1])

10
10


In [88]:
#access 5,6,7 i.e. elements in same row
print(li[1][:3])
print(a[1,:3])
print(a[1][:3])


[5, 6, 7]
[5 6 7]
[5 6 7]


In [89]:
#access 4,8 ,12:elements in the same column
print(li[0:3][3])#this gives an error,see why in the next cell

IndexError: list index out of range

In [90]:
x=li[0:3]
print(x)
print(x[3])#so first list is converted to sliced list and then we can access
# element but there are indexes till 2 in x so we get an error

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


IndexError: list index out of range

In [94]:
x=li[0:3]
print(x)

print('output:',x[2])

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
output: [9, 10, 11, 12]


In [92]:
print(li[0:3][2])#so we are not getting the output we wanted which was 4,8,12

[9, 10, 11, 12]


In [100]:
#but numpy arrays can make our life easy for accessing elements in same column
print(a[:3,3])#accessing 3rd index for rows 0 to 2

[ 4  8 12]


In [102]:
#extract 10 11 14 15 using numpy
print(a[2:4,1:3])

[[10 11]
 [14 15]]


In [103]:
#trying to do it using list
print(li[2:4][1:3])#did not work

[[13, 14, 15, 16]]


#### NUMPY MAKES OUR LIFE VERY EASY for working on matrices

In [110]:
#ASSIGNMENT: access elements in numpy array
li=[]
ctr=1
for i in range(4):
    temp=[]
    for j in range(5):
        temp.append(ctr)
        ctr+=1
    li.append(temp)
print(li)
a=np.array(li)
print(a)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [111]:
#access 11,12,13
print(a[2,0:3])

[11 12 13]


In [112]:
#access 9,14,19
print(a[1:4,3])

[ 9 14 19]


In [113]:
#access 3rd and 4th row
print(a[2:4])

[[11 12 13 14 15]
 [16 17 18 19 20]]


In [114]:
#access 7,8,12,13
print(a[1:3,1:3])

[[ 7  8]
 [12 13]]


### MATHEMATICAL OPERATIONS comparison of NUMPY WITH NORMAL LISTS

In [4]:
li=[1,2,3,4,5]
a=np.random.randint(1,20,5)
b=np.random.randint(1,10,7)
print(li)
print(a)
print(b)


[1, 2, 3, 4, 5]
[17  6  7  2  7]
[9 3 2 9 3 9 2]


In [5]:
#adding 1 to each element in a list
li= [i+1 for i in li]
print(li)

[2, 3, 4, 5, 6]


In [6]:
#adding 1 to each element in numpy array
a=a+1
b=b+5
print(a)
print(b)

[18  7  8  3  8]
[14  8  7 14  8 14  7]


In [9]:
#adding two matrices(can only be added if dimension is same)
c=np.random.randint(1,10,7)
d=b+c
print(c)
print(d)

[9 4 7 2 3 3 5]
[23 12 14 16 11 17 12]


In [10]:
#subtracting matrices value by value
d=b-c
print(d)

[ 5  4  0 12  5 11  2]


In [11]:
#multiplying matrices value by value
d=b*c
print(d)

[126  32  49  28  24  42  35]


In [12]:
#dividing matrices value by value
d=b/c
print(d)

[1.55555556 2.         1.         7.         2.66666667 4.66666667
 1.4       ]


In [13]:
#dividing matrices value by value(floor division)
d=b//c
print(d)

[1 2 1 7 2 4 1]


In [14]:
#exponientiate one matrix to another
d=b**c
print(d)

[-813789696       4096     823543        196        512       2744
      16807]


In [15]:
#get sum of array
print(a.sum())

44


In [16]:
#get mean or average
print(a.mean())

8.8


In [17]:
#get min element
print(a.min())

3


In [18]:
#get index of min element
print(a)
print(a.argmin())#3 is present at index 3

[18  7  8  3  8]
3


In [19]:
#get max element
print(a.max())

18


In [20]:
#get index of max element
print(a)
print(a.argmax())#18 is present at index 0

[18  7  8  3  8]
0


#### LOGICAL  and COMPARISON OPERATIONS ON MATRICES

In [23]:
print(b)
print(c)

[14  8  7 14  8 14  7]
[9 4 7 2 3 3 5]


In [25]:
print(b>c)#compares element wise(but dimension of arrays should be same)

[ True  True False  True  True  True  True]


In [26]:
print(b==c)

[False False  True False False False False]


In [27]:
print(b<c)

[False False False False False False False]


In [33]:
#logical operations on matrix
print(np.logical_or(b,c))#logical or
print(np.logical_and(b,c))#logical and


[ True  True  True  True  True  True  True]
[False False False False False False False]


In [35]:
#logical not of an array tells how many elements are 0
print(np.logical_not(a))
a[2]=0#updating 2nd index to 2
print(np.logical_not(a))

[False False False False False]
[False False  True False False]


## BOOLEAN INDEXING

In [36]:
a=np.random.randint(1,20,9)
print(a)

[ 4  7  1 10  4 10 18  9 19]


In [40]:
b=a<10
print(b)

[ True  True  True False  True False False  True False]


In [41]:
#if a boolean array is passed instead of index we will get only those elements
#for which the boolean index is true
print(a[b])#b is the boolean array

[4 7 1 4 9]


In [43]:
#we can do it directly also by specifying conditions
ans=a[a<10]
print(ans)

[4 7 1 4 9]


In [48]:
#using more than one condition
ans=a[(a>5) & (a<19)]#logical and for conditions
print(ans)

[ 7 10 10 18  9]


In [53]:
#changing multiple values in array
b=np.random.randint(5,25,9)
c=b
print(b)
c[:4]=15#makes all elements lesser than 4th index to 15
print(c)
print(b)#so numpy arrays are also mutable b and c point to the same array

[18 15 12  6 23 11 22 17 12]
[15 15 15 15 23 11 22 17 12]
[15 15 15 15 23 11 22 17 12]


In [55]:
#updating values based on some condition
b=np.random.randint(5,25,9)
print(b)
b[b>15]=100
print(b)

[ 6 24 15 13 24 21  8 18 16]
[  6 100  15  13 100 100   8 100 100]


In [56]:
#get indexes where condition is satisfied
print(np.where(b==100))#np.where gives us indexes based on some condition
#where it is being satisfied

(array([1, 4, 5, 7, 8], dtype=int64),)


In [60]:
#combining conditions of 2 arrays
a=np.array(['t','b','r','d','e','f','z','a','k'])
#dimensions should be same for a and b
print(a)
print(b)
#combine 2 arrays
ind=np.where(b==100)

print(a[ind])

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a' 'k']
[  6 100  15  13 100 100   8 100 100]
['b' 'e' 'f' 'a' 'k']


In [65]:
#ASSIGNMENT NON ZERO ELEMENTS INDEX
a=np.array([1,2,0,0,4,0])
print(list(np.where(a!=0)))

[array([0, 1, 4], dtype=int64)]


In [67]:
# ASS:- FIND INDEX OF ELEMENTS WHICH ARE MULTIPLE OF 3
a=np.linspace(1,19,10,dtype=int)
print(a)
print(np.where(a%3==0))

[ 1  3  5  7  9 11 13 15 17 19]
(array([1, 4, 7], dtype=int64),)


In [69]:
# ASS:- replace odd digits with -1 and print the array
a=np.linspace(1,10,10,dtype=int)
print(a)
a[a%2!=0]=-1
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
[-1  2 -1  4 -1  6 -1  8 -1 10]


In [4]:
# ASS:- replace the first occurence of maximum value by 0
a=np.array([11,2,13,1,15,6,27,8,19])
ind=a.argmax()#get index of maximum element
print(ind)
a[ind]=0
print(a)

6
[11  2 13  1 15  6  0  8 19]


In [77]:
# ASS:- negate all elements which are between 3 and 8
a=np.linspace(1,10,10,dtype=int)
print(a)
a[(a>=3) & (a<=8)]=-a[(a>=3) & (a<=8)]
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2 -3 -4 -5 -6 -7 -8  9 10]


In [95]:
#ASS:- print age and heights of those students which are above 155 cm
age=np.random.randint(10,22,size=10)
height=np.random.randint(140,180,size=10)
print(age)
print(height)
ind=np.where(height>155)#get index of those students whose height is above 155
print(ind)#index is a tuple where at 0th index we have indexes
for i in ind[0]:
    print(age[i],height[i])

[19 18 19 10 19 10 16 11 12 15]
[153 162 171 157 167 145 163 176 145 150]
(array([1, 2, 3, 4, 6, 7], dtype=int64),)
18 162
19 171
10 157
19 167
16 163
11 176


## BOOLEAN INDEXING ON 2d arrays

In [16]:
a=np.random.randint(1,30,(5,6))#if end is not given then we need to specify
#explicitly, if it is there then third parameter signifies size
print(a)

[[21 13 26 28 17 28]
 [13 18 24  7  8 21]
 [ 8  5 24  2 16 28]
 [11 21 16  3  2  8]
 [ 8  2 21 13 27 25]]


In [17]:
boolean=a>20
print(boolean)

[[ True False  True  True False  True]
 [False False  True False False  True]
 [False False  True False False  True]
 [False  True False False False False]
 [False False  True False  True  True]]


In [18]:
print(a[boolean])#we get the ans as 1d array
#note:- if dimension of boolean array is not same as the original array we get 
#error

[21 26 28 28 24 21 24 28 21 21 27 25]


In [19]:
c=np.random.randint(1,10,(2,2))
c[boolean]#error

IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 5

In [20]:
#example change elements greater than 20
a[a>20]=100#same as 1d array
print(a)

[[100  13 100 100  17 100]
 [ 13  18 100   7   8 100]
 [  8   5 100   2  16 100]
 [ 11 100  16   3   2   8]
 [  8   2 100  13 100 100]]


In [21]:
print(a)

[[100  13 100 100  17 100]
 [ 13  18 100   7   8 100]
 [  8   5 100   2  16 100]
 [ 11 100  16   3   2   8]
 [  8   2 100  13 100 100]]


In [22]:
#change values of column 3 where value is 100
boolean_arr=a[:,3]==100
print(boolean_arr)
a[boolean_arr,3]=99#3 is the column number
print(a)

[ True False False False False]
[[100  13 100  99  17 100]
 [ 13  18 100   7   8 100]
 [  8   5 100   2  16 100]
 [ 11 100  16   3   2   8]
 [  8   2 100  13 100 100]]


In [23]:
#note:- always use boolean arrays for manipulating indexes

In [24]:
#ASS:- sort the 1st column of numpy array in ascending order
a=[[21,20,19,18,17],[16,15,14,13,12],[11,10,9,8,7],[6,5,4,3,2]]
b=np.array(a)
print(b,end='\n\n')

#sorting
b[:,1].sort()
print(b)

[[21 20 19 18 17]
 [16 15 14 13 12]
 [11 10  9  8  7]
 [ 6  5  4  3  2]]

[[21  5 19 18 17]
 [16 10 14 13 12]
 [11 15  9  8  7]
 [ 6 20  4  3  2]]


## BROADCASTING-HOW TO TREAT THE UNEQUAL SIZE OF ARRAYS

In [26]:
#SUPPOSE WE HAVE 2 ARRAYS A AND B OF DIMENSION (2,3) AND (3,2) AND IF WE TRY
#TO PERFORM ANY MATHEMATICAL OPERATION ON IT THEN WE WOULD GET AN ERROR THAT 
#DIMENSIONS DONT MATCH,SO IN BROADCASTING WE WORK TOWARDS RESOLVING THAT ERROR
import numpy as np

In [27]:
#Rules of compatibility for performing operations
# 1. Dimensions should be same
# 2. One of them is a 1d array

In [28]:
#same dimensions
x=np.random.randint(1,10,(3,3))
y=np.random.randint(1,10,(3,3))
print(x)
print(y)
ans=x-y
print(ans)

[[7 9 7]
 [7 1 5]
 [2 2 9]]
[[5 2 7]
 [4 5 9]
 [2 7 8]]
[[ 2  7  0]
 [ 3 -4 -4]
 [ 0 -5  1]]


In [30]:
#one of them is a 1d array
x=np.random.randint(1,10,(3,3))
y=np.random.randint(1,10,3)
print(x)
print(y,end='\n\n')
ans=x-y
print(ans)# the 1d array is subtracted element by element from the 
#rows of 2d arrays,happening internally

[[7 5 3]
 [8 9 6]
 [3 8 2]]
[1 6 8]

[[ 6 -1 -5]
 [ 7  3 -2]
 [ 2  2 -6]]


In [54]:
#one of them is a 1d array
x=np.random.randint(1,10,(3,3))
y=np.random.randint(1,10,1)
print(x)
print(y,end='\n\n')
ans=x-y
print(ans)# the 1d array is subtracted element by element from the 
#rows of 2d arrays,happening internally

[[1 1 8]
 [5 2 3]
 [9 9 6]]
[2]

[[-1 -1  6]
 [ 3  0  1]
 [ 7  7  4]]


In [4]:
#one of them is a 1d array
x=np.random.randint(1,10,(3,3))
y=np.random.randint(1,10,2)#gives error
print(x)
print(y,end='\n\n')
ans=x-y
print(ans)# the 1d array is subtracted element by element from the 
#rows of 2d arrays,happening internally

[[7 2 9]
 [5 7 4]
 [8 7 1]]
[5 7]



ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [56]:
# we can only perform operations if one array is 2d of shape mxn 
# and second is 1d array of shape 1 or m or n

In [33]:
#shape not compatible
x=np.random.randint(1,10,(2,3))
y=np.random.randint(1,10,(3,2))
print(x)
print(y,end='\n\n')


[[5 8 9]
 [7 3 3]]
[[5 3]
 [5 6]
 [6 2]]



In [34]:
ans=x-y
print(ans)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [35]:
#we can make them compatible,there are several ways:-
# 1.transposing one of them-can only be done if their dimensions are symmetrical
#i.e. (2,3)(3,2)
# 2.resize()
# 3.reshape()


In [38]:
#transpose
print(x)
print(y,end='\n\n')
z=np.transpose(y)
print(z)

ans=x-z
print(ans)#no error

[[5 8 9]
 [7 3 3]]
[[5 3]
 [5 6]
 [6 2]]

[[5 5 6]
 [3 6 2]]
[[ 0  3  3]
 [ 4 -3  1]]


In [43]:
#2.resize:- returns a resized array with same elements
li=[1,2,3]
a=np.array(li)
print(a)
print(np.resize(a,(4)))
print(np.resize(a,(5)))
print(np.resize(a,(6)))#observe that it returns redundant values from array a

[1 2 3]
[1 2 3 1]
[1 2 3 1 2]
[1 2 3 1 2 3]


In [48]:
#2.resize:- returns a resized array with same elements (repeating in order if
#indexes are more than original array
li=[[1,2,3],[4,5,6]]
a=np.array(li)
print(a)
print('---------------------')
print(np.resize(a,(4)))
print('---------------------')
print(np.resize(a,(5)))
print('---------------------')
print(np.resize(a,(6)))
print('---------------------')
print(np.resize(a,(5,6)))
print('---------------------')
print(np.resize(a,(6,7)))#observe that it returns redundant values from array a

[[1 2 3]
 [4 5 6]]
---------------------
[1 2 3 4]
---------------------
[1 2 3 4 5]
---------------------
[1 2 3 4 5 6]
---------------------
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]
---------------------
[[1 2 3 4 5 6 1]
 [2 3 4 5 6 1 2]
 [3 4 5 6 1 2 3]
 [4 5 6 1 2 3 4]
 [5 6 1 2 3 4 5]
 [6 1 2 3 4 5 6]]


In [50]:
#3.reshape:returns a reshaped array without changing its data(the no. of
#elements in changed array should be same as they were in original
li=[[1,2,3],[4,5,6]]
a=np.array(li)
print(a)
print('---------------------')
b=np.reshape(a,(5,6))#gives error as there are 6 elements in a and there would 
#be 30 elements in array of shape(5,6)



[[1 2 3]
 [4 5 6]]
---------------------


ValueError: cannot reshape array of size 6 into shape (5,6)

In [51]:
#3.reshape:returns a reshaped array without changing its data
li=[[1,2,3],[4,5,6]]
a=np.array(li)
print(a)
print('---------------------')
#no error
b=np.reshape(a,(3,2)) 
print(b)
print('---------------------')
c=np.reshape(a,(2,3))
print(c)
print('---------------------')

[[1 2 3]
 [4 5 6]]
---------------------
[[1 2]
 [3 4]
 [5 6]]
---------------------
[[1 2 3]
 [4 5 6]]
---------------------


In [58]:
#EXAMPLES OF BROADCASTING
#1.arrays of shape(1,3) and (3,1)
a=np.random.randint(1,10,(1,3))
print(a)
print('---------------------')
b=np.random.randint(1,10,(3,1))
print(b)
print('---------------------')
ans=a-b#broadcasting happens and we get output as a 3x3 matrix
print(ans)
print('---------------------')


[[6 2 1]]
---------------------
[[6]
 [5]
 [9]]
---------------------
[[ 0 -4 -5]
 [ 1 -3 -4]
 [-3 -7 -8]]
---------------------


In [59]:
#2.arrays of shape(1,3) and (1,1)
a=np.random.randint(1,10,(1,3))
print(a)
print('---------------------')
b=np.random.randint(1,10,(1,1))
print(b)
print('---------------------')
ans=a-b#broadcasting happens and we get output as a 1x3 matrix
print(ans)
print('---------------------')


[[6 5 5]]
---------------------
[[9]]
---------------------
[[-3 -4 -4]]
---------------------


In [61]:
#3. arrays of shape(1,3) and (3,3)
a=np.random.randint(1,10,(1,3))
print(a)
print('---------------------')
b=np.random.randint(1,10,(3,3))
print(b)
print('---------------------')
ans=a-b#broadcasting happens and we get output as a 3x3 matrix
print(ans)
print('---------------------')


[[9 3 9]]
---------------------
[[1 3 8]
 [1 6 2]
 [4 3 3]]
---------------------
[[ 8  0  1]
 [ 8 -3  7]
 [ 5  0  6]]
---------------------


## WORKING ON A REAL LIFE EXAMPLE

In [14]:
#year2017.csv
#calculate killed + wounded 
import csv
import numpy as np

with open(r'C:\Users\shubh\Desktop\Coding Ninjas Data Science\11. NumPy\33-34\terrorismData.csv',encoding='utf8') as file_obj:
    file_data=csv.DictReader(file_obj,skipinitialspace=True)
    killed=[]
    wounded=[]
    country=[]
    for row in file_data:
        killed.append(row['Killed'])
        wounded.append(row['Wounded'])
        country.append(row['Country'])
np_killed=np.array(killed,dtype=int)#error as we directly convert it into int,
#we need to convert it to float first,while also dealing with '' values where
#there is no value,but we cannot remove those values as it would lead to value
#mismatch in the arrays,so we need to make sure that length of arrays should remain
#same


ValueError: invalid literal for int() with base 10: '1.0'

In [19]:
#correcting the errors
#year2017.csv
#calculate killed + wounded 
import csv
import numpy as np

with open(r'C:\Users\shubh\Desktop\Coding Ninjas Data Science\11. NumPy\33-34\terrorismData.csv',encoding='utf8') as file_obj:
    file_data=csv.DictReader(file_obj,skipinitialspace=True)
    killed=[]
    wounded=[]
    country=[]
    for row in file_data:
        killed.append(row['Killed'])
        wounded.append(row['Wounded'])
        country.append(row['Country'])

np_killed=np.array(killed)
np_wounded=np.array(wounded)
np_country=np.array(country)

#changing "" values to 0
np_killed[np_killed=='']='0.0'
np_wounded[np_wounded=='']='0.0'
#converting to float
np_killed=np.array(np_killed,dtype=float)
np_wounded=np.array(np_wounded,dtype=float)

#finding killed + wounded in India
boolean=np_country=='India'
killed_wounded=np_killed+np_wounded
ans=killed_wounded[boolean]
print(np.sum(ans))#killed and wounded in india
print(np.sum(killed_wounded))#total killed and wounded

48321.0
935737.0


In [21]:
#ASSIGNMENT:count of killed in United States
with open(r'C:\Users\shubh\Desktop\Coding Ninjas Data Science\11. NumPy\33-34\terrorismData.csv',encoding='utf8') as file_obj:
    file_data=csv.DictReader(file_obj,skipinitialspace=True)
    killed=[]
    country=[]
    for row in file_data:
        killed.append(row['Killed'])
        country.append(row['Country'])

#data cleaning
np_killed=np.array(killed)
np_killed[np_killed=='']='0.0'
np_killed=np.array(np_killed,dtype=float)
print(np.sum(np_killed))
#boolean array for USA
boolean=np_country=='United States'
ans=np_killed[boolean]
print(np.sum(ans))

411868.0
3771.0


In [24]:
#ASSIGNMENT:find value of killed column only in United States
with open(r'C:\Users\shubh\Desktop\Coding Ninjas Data Science\11. NumPy\33-34\terrorismData.csv',encoding='utf8') as file_obj:
    file_data=csv.DictReader(file_obj,skipinitialspace=True)
    killed=[]
    country=[]
    for row in file_data:
        killed.append(row['Killed'])
        country.append(row['Country'])

#data cleaning
np_killed=np.array(killed)
np_killed[np_killed=='']='0.0'
np_killed=np.array(np_killed,dtype=float)
#boolean array for USA
boolean=np_country=='United States'
ans=np_killed[boolean]
for i in ans:
    print('Killed',int(i))

Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 1
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 2
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 2
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
K

Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 1
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 2
Killed 1
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 1
Killed 0
Killed 1
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 1
Killed 0
Killed 0
Killed 1
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 1
Killed 1
Killed 1
Killed 0
Killed 1
Killed 0
Killed 2
Killed 0
Killed 0
K

Killed 0
Killed 1
Killed 0
Killed 0
Killed 0
Killed 2
Killed 1
Killed 1
Killed 0
Killed 3
Killed 4
Killed 2
Killed 1
Killed 5
Killed 0
Killed 1
Killed 0
Killed 0
Killed 1
Killed 0
Killed 1
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 1
Killed 0
Killed 0
Killed 1
Killed 2
Killed 0
Killed 3
Killed 0
Killed 0
Killed 0
Killed 0
Killed 1
Killed 2
Killed 9
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 6
Killed 0
Killed 3
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 10
Killed 0
Killed 1
Killed 0
Killed 0
Killed 0
Killed 0
Killed 3
Killed 16
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 1
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 50
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 6
Killed 1
Killed 0
Killed 0
Killed 4
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 0
Killed 2
Killed 0
Killed 0
Killed 

# FINAL ASSIGNMENTS

In [5]:
import numpy as np
import csv

In [6]:
#ASS-1:find no. of attacks held between day 10 and day 20 and print it
with open(r'C:\Users\Shubh Gaur\Desktop\Coding Ninjas Data Science\11. NumPy\Assignment\terrorismData.csv',encoding='utf8') as obj:
    data=csv.DictReader(obj,skipinitialspace=True)
    day=[]
    for row in data:
        day.append(row['Day'])
#Numpy array
np_day=np.array(day,dtype=int)
boolean=(np_day>=10) & (np_day<=20)
print(len(np_day[boolean]))


66330


In [14]:
#ASS-2:find attacks held between 1 Jan 2010 and 31 Jan 2010 both inclusive
with open(r'C:\Users\shubh\Desktop\Coding Ninjas Data Science\11. NumPy\Assignment\terrorismData.csv',encoding='utf8') as obj:
    data=csv.DictReader(obj,skipinitialspace=True)
    day=[]
    month=[]
    year=[]
    for row in data:
        day.append(row['Day'])
        month.append(row['Month'])
        year.append(row['Year'])

#numpy arrays
np_day=np.array(day,dtype=int)
np_month=np.array(month,dtype=int)
np_year=np.array(year,dtype=int)

#filtering data
boolean_year=np_year==2010
boolean_month=np_month==1
boolean_day= (np_day>=1) & (np_day<=31)
ans=np_day[(boolean_year)&(boolean_month)&(boolean_day)]
print(len(ans))

271


In [20]:
#ASS-3find the attack with most casualty during may 1999 to july 1999
with open(r'C:\Users\shubh\Desktop\Coding Ninjas Data Science\11. NumPy\Assignment\terrorismData.csv',encoding='utf8') as obj:
    data=csv.DictReader(obj,skipinitialspace=True)
    killed=[]
    wounded=[]
    group=[]
    city=[]
    for row in data:
        month=int(row['Month'])
        if row['Year']=='1999' and (month>=5 and month<=7):
            killed.append(row['Killed'])
            wounded.append(row['Wounded'])
            group.append(row['Group'])
            city.append(row['City'])
    #cleaning data
    np_killed=np.array(killed)
    np_killed[np_killed=='']='0.0'
    np_wounded=np.array(wounded)
    np_wounded[np_wounded=='']='0.0'
    
    #---------------------------
    np_killed=np.array(np_killed,dtype=float)
    np_wounded=np.array(np_wounded,dtype=float)
    np_casualties=np_killed+np_wounded
    
    maxIndex=np.argmax(np_casualties)
    
    print(np_casualties[maxIndex],city[maxIndex],group[maxIndex])
    
    

300.0 Unknown Unknown
300.0


In [22]:
#ASS-4: find the casualties in red corridor states
with open(r'C:\Users\shubh\Desktop\Coding Ninjas Data Science\11. NumPy\Assignment\terrorismData.csv',encoding='utf8') as obj:
    data=csv.DictReader(obj,skipinitialspace=True)
    killed=[]
    wounded=[]
    group=[]
    city=[]
    for row in data:
        state=row['State']
        if state=="Jharkhand" or state=="Odisha" or state=="Andhra Pradesh" or state=="Chhattisgarh":
            killed.append(row['Killed'])
            wounded.append(row['Wounded'])
    #cleaning data
    np_killed=np.array(killed)
    np_killed[np_killed=='']='0.0'
    np_wounded=np.array(wounded)
    np_wounded[np_wounded=='']='0.0'
    #---------------------------
    np_killed=np.array(np_killed,dtype=float)
    np_wounded=np.array(np_wounded,dtype=float)
    np_casualties=np_killed+np_wounded
    print(int(np.sum(np_casualties)))
    

5628


In [24]:
#ASS-4: find the casualties in red corridor states
with open(r'C:\Users\shubh\Desktop\Coding Ninjas Data Science\11. NumPy\Assignment\terrorismData.csv',encoding='utf8') as obj:
    data=csv.DictReader(obj,skipinitialspace=True)
    killed=[]
    wounded=[]
    for row in data:
        state=row['State']
        if state=="Jharkhand" or state=="Odisha" or state=="Andhra Pradesh" or state=="Chhattisgarh":
            killed.append(row['Killed'])
            wounded.append(row['Wounded'])
    #cleaning data
    np_killed=np.array(killed)
    np_killed[np_killed=='']='0.0'
    np_wounded=np.array(wounded)
    np_wounded[np_wounded=='']='0.0'
    #---------------------------
    np_killed=np.array(np_killed,dtype=float)
    np_wounded=np.array(np_wounded,dtype=float)
    np_casualties=np_killed+np_wounded
    print(int(np.sum(np_casualties)))
    

5628


In [2]:
#ASS-5: find top 5 Indian cities with max number of casualties
with open(r'C:\Users\shubh\Desktop\Coding Ninjas Data Science\11. NumPy\Assignment\terrorismData.csv',encoding='utf8') as obj:
    data=csv.DictReader(obj,skipinitialspace=True)
    killed=[]
    wounded=[]
    city=[]
    for row in data:
        country=row['Country']
        if country=='India':
            killed.append(row['Killed'])
            wounded.append(row['Wounded'])
            city.append(row['City'])
    #cleaning data
    np_killed=np.array(killed)
    np_killed[np_killed=='']='0.0'
    np_wounded=np.array(wounded)
    np_wounded[np_wounded=='']='0.0'
    #---------------------------
    np_killed=np.array(np_killed,dtype=float)
    np_wounded=np.array(np_wounded,dtype=float)
    np_casualties=np_killed+np_wounded
    np_city=np.array(city)

ctr=1
while ctr<=5:
    maxIndex=np.argmax(np_casualties)
    print(np_city[maxIndex],np_casualties[maxIndex])
    #resetting values at maxIndex
    np_city[maxIndex]='' 
    np_casualties[maxIndex]=-100.0
    ctr+=1
    
    

Mumbai 1005.0
Dispur 272.0
Jhargam 255.0
Chennai 232.0
New Delhi 210.0


In [7]:
#ASS-6: find most frequent day of attacks
with open(r'C:\Users\shubh\Desktop\Coding Ninjas Data Science\11. NumPy\Assignment\terrorismData.csv',encoding='utf8') as obj:
    data=csv.DictReader(obj,skipinitialspace=True)
    day=[]
    for row in data:
        day.append(row['Day'])
np_day=np.array(day,dtype=int)
unique,count=np.unique(np_day,return_counts=True)
print(unique)
print(count)
maxIndex=np.argmax(count)
print('ans:-')
print(unique[maxIndex],np.max(count))
            


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]
[ 891 6344 5954 6011 6153 5844 5781 5997 5859 6057 6064 5936 6012 6043
 6028 6500 6112 5852 5880 5973 5930 5827 5799 5782 5752 5875 5823 5937
 6027 5507 5046 3095]
ans:-
15 6500
